version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: earthworm_dev
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mysql://root:password@mysql:3306/earthworm_dev
    ports:
      - "3001:3001"
    depends_on:
      - mysql
